extends Node

const SHOPPERS = [Scenes.CHARACTER_SOLDIER, Scenes.CHARACTER_WARRIOR]

const STATS = [Scenes.STAT_DEFENSE, Scenes.STAT_STRENGTH]

const SOURCES = [Scenes.SOURCE_APPLE_TREE, Scenes.SOURCE_CHICKEN]

const INGREDIENTS = [Scenes.INGREDIENT_APPLE, Scenes.INGREDIENT_EGG]
